org.gradle.jvmargs=-Xmx3G

mod_id=ftbessentials
readable_name=FTB Essentials
archives_base_name=ftb-essentials
maven_group=dev.ftb.mods

minecraft_version=26.3
supported_minecraft_versions=26.3
minecraft_version_range_maven=[26.3,27)
minecraft_version_range_semver=>=26.3.0

mod_version=5
mod_author=FTB Team

# Deps
neoforge_version=26.3.0.1-beta
neoforge_version_range=[26.3.0.1-beta,27)
neoforge_loader_version=4

fabric_loader_version=0.19.5
fabric_api_version=0.160.5+26.3
fabric_api_version_range=>=0.160.5+26.3

ftb_library_version=26.3.0.1-SNAPSHOT
ftb_library_version_range_semver=>=26.1.2.1
ftb_library_version_range_maven=[26.1.2.1,27)

ftb_ranks_version=26.3.0.4-SNAPSHOT
ftb_ranks_version_range_semver=>=26.1.0.1
ftb_ranks_version_range_maven=[26.1.0.1,27)

# common curseforge project for forge and fabric
curseforge_id=410811
