name: Java CI - Build on Push

on:
  push:
    branches: [ main, dev, "1.*" ]
  workflow_dispatch:
    inputs:
      skip_maven_publish:
        description: 'Skip Maven publishing'
        required: true
        default: 'true'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: FTBTeam/mods-meta/.github/workflows/standard-release.yml@main
    with:
      curse-publish-task: ""
      maven-snapshots: false
      java-version: 17
